# Образ для запуска
image: images.mfms.ru/gitlab/builder/android:31_02r

# Задаем переменные окружения
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

# Кэш для ускорения шагов для текущего пайплайна
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/wrapper
    - .gradle/caches

default:
  before_script:
    - chmod +x ./gradlew
    - export GRADLE_USER_HOME=$PWD/.gradle

# Основные шаги
stages:
  - lint
  - test
  - release

linting:
  stage: lint
  script:
    - bundle exec fastlane sdkLint
  only:
    - merge_requests

unitTests:
  stage: test
  script:
    - bundle exec fastlane sdkUnitTests
  only:
    - merge_requests

release:
  stage: release
  script:
    - ./gradlew assemble
    - ./gradlew publish
    - git config --global user.email "vladimir.rybalka@edna.ru"
    - git config --global user.name "Vladimir"
    - |
      if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" = "master" ]; then
        version=$(grep "version=" gradle.properties | cut -d'=' -f2)
        IFS='.' read -ra VERSION_PARTS <<< "$version"
        if [[ ${#VERSION_PARTS[@]} -ge 2 && ${VERSION_PARTS[1]} =~ ^[0-9]+$ ]]; then
          VERSION_PARTS[1]=$((VERSION_PARTS[1] + 1))
          newVersion="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.0"
          git remote rm gitlab_origin || true
          git remote add gitlab_origin http://$SDK_ACCESS_TOKEN_NAME:$SDK_ACCESS_TOKEN@gitlab.mfms/android/chat-center/chatcenter-sdk.git
          git fetch --all
          if git show-ref --verify --quiet refs/heads/develop; then
            git checkout develop
            git pull origin develop
          else
            git checkout -b develop origin/develop
          fi
          echo "Old version is $version. New version is $newVersion"
          git tag "Release v$version"
          git push --tags http://$SDK_ACCESS_TOKEN_NAME:$SDK_ACCESS_TOKEN@gitlab.mfms/android/chat-center/chatcenter-sdk.git HEAD:develop
          sed -i "s/^version=.*/version=$newVersion/g" gradle.properties
          git add gradle.properties
          git diff --quiet && git diff --staged --quiet || git commit -m "Starting development of v$newVersion"
          git push -f http://$SDK_ACCESS_TOKEN_NAME:$SDK_ACCESS_TOKEN@gitlab.mfms/android/chat-center/chatcenter-sdk.git HEAD:develop
        else
          echo "Version format is not supported for auto increment"
        fi
      fi
  only:
    - merge_requests
  artifacts:
    paths:
      - "./**/build/outputs/aar/*.aar"
    expire_in: 1 hrs
  when: manual
