# Образ для запуска
image: images.mfms.ru/gitlab/builder/android:31_01r

# Задаем переменные окружения
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

# Кэш для ускорения шагов для текущего пайплайна
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Выполняется до скриптов 
# - устанавливаем bundler
# - устанавливаем через него нужные зависимости
# - делаем градл выполняемым 
# - задаем путь для GRADLE_USER_HOME
before_script:
  - gem install bundler
  - bundle install
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=$PWD/.gradle

# Основные шаги
stages:
  # - environment
  # - build
  - lint
  - test

linting:
  stage: lint
  script:
    - bundle exec fastlane sdkLint
  only:
    - merge_requests

unitTests:
  stage: test
  script:
    - bundle exec fastlane sdkUnitTests
  only:
    - merge_requests
