# Образ для запуска
image: images.mfms.ru/gitlab/builder/android:31_02r

# Задаем переменные окружения
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

# Кэш для ускорения шагов для текущего пайплайна
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/wrapper
    - .gradle/caches

default:
  before_script:
    - chmod +x ./gradlew
    - export GRADLE_USER_HOME=$PWD/.gradle

# Основные шаги
stages:
  - lint
  - test
  - buildAndPublishAar

linting:
  stage: lint
  script:
    - bundle exec fastlane sdkLint
  only:
    - merge_requests

unitTests:
  stage: test
  script:
    - bundle exec fastlane sdkUnitTests
  only:
    - merge_requests

buildAndPublishAAR:
  stage: buildAndPublishAar
  script:
    - ./gradlew assemble
    - ./gradlew publish
  only:
    - merge_requests
  artifacts:
    paths:
      - "./**/build/outputs/aar/*.aar"
    expire_in: 2 hrs
  when: manual