# Основные шаги
stages:
  # - environment
  # - build
  - test


# .updateContainerJob:
#   image: docker:stable
#   stage: environment
#   services:
#     - docker:dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker pull --quiet $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG || true
#     - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# updateContainer:
#   extends: .updateContainerJob
#   only:
#     changes:
#       - Dockerfile

# ensureContainer:
#   extends: .updateContainerJob
#   allow_failure: true
#   before_script:
#     - "mkdir -p ~/.docker && echo '{\"experimental\": \"enabled\"}' > ~/.docker/config.json"
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - |
#       if docker manifest inspect $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG > /dev/null; then
#         echo 'Skipping job since there is already an image with this tag'
#         exit 0
#       fi

# .build_job:
#   image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#   stage: build
#   before_script:
#     # We store this binary file in a project variable as hex with this command: `xxd -p android-app.jks`
#     # Then we convert the hex back to a binary file
#     - echo "$signing_jks_file_hex" | xxd -r -p - > android-signing-keystore.jks
#     - export VERSION_CODE="$CI_PIPELINE_IID" && echo "$VERSION_CODE"
#     - export VERSION_SHA="${CI_COMMIT_SHA:0:8}" && echo "$VERSION_SHA"
#   after_script:
#     - rm -f android-signing-keystore.jks || true
#   artifacts:
#     paths:
#       - app/build/outputs

# buildDebug:
#   extends: .build_job
#   script:
#     - bundle exec fastlane buildDebug

# buildRelease:
#   extends: .build_job
#   script:
#     - bundle exec fastlane buildRelease
#   environment:
#     name: production

unitTests:
  # image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: test
  # dependencies:
  #   - buildDebug
  script:
    - bundle exec fastlane sdkUnitTests
