package im.threads.ui.utils.preferences

import im.threads.business.utils.preferences.PrefUtilsBaseKeys

class PrefUtilsKeys : PrefUtilsBaseKeys() {
    val APP_STYLE = "APP_STYLE"
    val STORAGE_PERMISSION_DESCRIPTION_DIALOG_STYLE =
        "STORAGE_PERMISSION_DESCRIPTION_DIALOG_STYLE"
    val RECORD_AUDIO_PERMISSION_DESCRIPTION_DIALOG_STYLE =
        "RECORD_AUDIO_PERMISSION_DESCRIPTION_DIALOG_STYLE"
    val CAMERA_PERMISSION_DESCRIPTION_DIALOG_STYLE =
        "CAMERA_PERMISSION_DESCRIPTION_DIALOG_STYLE"
    val CLIENT_NOTIFICATION_DISPLAY_TYPE = "CLIENT_NOTIFICATION_DISPLAY_TYPE"
    val PREF_ATTACHMENT_SETTINGS = "PREF_ATTACHMENT_SETTINGS"

    override val allPrefKeys = super.allPrefKeys.apply {
        addAll(
            listOf(
                APP_STYLE,
                STORAGE_PERMISSION_DESCRIPTION_DIALOG_STYLE,
                RECORD_AUDIO_PERMISSION_DESCRIPTION_DIALOG_STYLE,
                CAMERA_PERMISSION_DESCRIPTION_DIALOG_STYLE,
                CLIENT_NOTIFICATION_DISPLAY_TYPE,
                PREF_ATTACHMENT_SETTINGS
            )
        )
    }
}
