package im.threads.ui.preferences

object PreferencesUiKeys {
    val APP_STYLE = "APP_STYLE"
    val STORAGE_PERMISSION_DESCRIPTION_DIALOG_STYLE =
        "STORAGE_PERMISSION_DESCRIPTION_DIALOG_STYLE"
    val RECORD_AUDIO_PERMISSION_DESCRIPTION_DIALOG_STYLE =
        "RECORD_AUDIO_PERMISSION_DESCRIPTION_DIALOG_STYLE"
    val CAMERA_PERMISSION_DESCRIPTION_DIALOG_STYLE =
        "CAMERA_PERMISSION_DESCRIPTION_DIALOG_STYLE"
    val CLIENT_NOTIFICATION_DISPLAY_TYPE = "CLIENT_NOTIFICATION_DISPLAY_TYPE"
    val PREF_ATTACHMENT_SETTINGS = "PREF_ATTACHMENT_SETTINGS"

    val allPrefKeys = mutableListOf(
        APP_STYLE,
        STORAGE_PERMISSION_DESCRIPTION_DIALOG_STYLE,
        RECORD_AUDIO_PERMISSION_DESCRIPTION_DIALOG_STYLE,
        CAMERA_PERMISSION_DESCRIPTION_DIALOG_STYLE,
        CLIENT_NOTIFICATION_DISPLAY_TYPE,
        PREF_ATTACHMENT_SETTINGS
    )
}
