package im.threads.business.preferences

internal class PrefKeysForMigration {
    val APP_MARKER_KEY = "APP_MARKER"
    val TAG_NEW_CLIENT_ID = "TAG_NEW_CLIENT_ID"
    val AUTH_TOKEN = "AUTH_TOKEN"
    val AUTH_SCHEMA = "AUTH_SCHEMA"
    val CLIENT_ID_SIGNATURE_KEY = "CLIENT_ID_SIGNATURE"
    val CLIENT_NAME = "DEFAULT_CLIENT_NAMETITLE_TAG"
    val EXTRA_DATA = "EXTRA_DATE"
    val TAG_CLIENT_ID_ENCRYPTED = "TAG_CLIENT_ID_ENCRYPTED"
}
