# Файл с конфигурацией fastlane
# Полная документация тут https://docs.fastlane.tools

default_platform(:android)

# Список лэйнов (шагов пайплайна)
platform :android do

  desc "Запуск модульных тестов для SDK"
  lane :demoLint do
    gradle(
      task: "app:lintDebug",
  )
  end

  desc "Запуск модульных тестов для Demo"
  lane :demoUnitTests do
    gradle(
      task: "app:testDebugUnitTest",
  )
  end

  desc "Запуск UI тестов для Demo"
  lane :demoUITests do
  end

end
