package im.threads.business.transport

object MessageAttributes {
    const val APP_MARKER_KEY = "appMarker"
    const val TYPE = "type"
    const val THREADS = "threads"
    const val APP_BUNDLE_KEY = "appBundle"
    const val CLIENT_ID = "clientId"
    const val CLIENT_ID_ENCRYPTED = "clientIdIsEncrypted"
    const val TEXT = "text"
    const val DATA = "data"
    const val DEVICE_ADDRESS = "deviceAddress"
    const val TYPING_DRAFT = "draft"
    const val QUOTES = "quotes"
    const val ATTACHMENTS = "attachments"
    const val UUID = "uuid"
    const val READ_MESSAGE_ID = "readInMessageIds"
    const val IS_MASS_PUSH_MESSAGE = "isMassPushMessage"
    const val CAMPAIGN = "campaign"
    const val RECEIVED_DATE = "receivedDate"
    const val ROUTING_PARAMS = "routingParams"
    const val PRIORITY = "priority"
    const val SKILL_ID = "skillId"
    const val EXPIRED_AT = "expiredAt"
    const val COORDINATES = "coordinates"
    const val AUTHORIZED = "authorized"
}
